---
name: Schedule - Sync secrets

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/schedule-sync-secrets.yaml

jobs:
  sync_secrets_and_vars:
    environment: production
    name: Sync secrets and variables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - bjw-s/home-ops
          - bjw-s/action-prettier-lint
    steps:
      - name: Sync Secrets and Variables
        uses: cbrgm/sync-secrets-action@v1
        with:
          github-token: ${{ secrets.SECRET_SYNC_TOKEN }}
          target: ${{ matrix.repo }}
          type: actions
          secrets: |
            REPODUSTER_APP_ID=${{ secrets.REPODUSTER_APP_ID }}
            REPODUSTER_APP_KEY_B64="${{ secrets.REPODUSTER_APP_KEY_B64 }}"
